# Description: Settings for the application
# mysql: MySQL database settings
mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  user: root
  password: root
  log_level: dev
# logger: Logger settings
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
# system: System settings
system:
  srv_name: GVB-Server
  host: "0.0.0.0"
  port: 8080
  env: release
